#!/usr/bin/env python3
"""
WoodHub — one-time data import helper.

Reads the original WoodHub.xlsx (three sheets: "Euca Chips Log Book",
"Euco Wood Log Book", "Assisment Log Book") and produces a single
`import.sql` file containing INSERT statements you can paste into your
Supabase project's SQL Editor (Project -> SQL Editor -> New query ->
paste -> Run).

This script only reads the spreadsheet and writes a local .sql file —
it does NOT need internet access, so it can be run from anywhere
(including this sandbox). Uploading the generated SQL to Supabase
happens in your browser, not from this script.

Usage:
    python3 import_data.py /path/to/WoodHub.xlsx
"""

import sys
import datetime
import openpyxl

COLUMN_MAP = [
    "material",
    "truck_number",
    "delivery_chalan",
    "driver_mobile",
    "transporter_name",
    "lorry_receipt",
    "transporter_mobile",
    "truck_capacity_mt",
    "truck_length",
    "transport_rate",
    "advance_paid",
    "advance_payment_date",
    "advance_paid_to",
    "final_payment",
    "loading_location",
    "weight_pi_yard_mt",
    "material_cost",
    "invoice_value_raised",
    "dispatch_date",
    "tax_invoice_number",
    "eway_bill_no",
    "reached_on",
    "wc_number",
    "weight_itc_yard",
    "weight_loss",
    "total_payment_to_transport",
    "bill_amount_raised_itc",
    "bill_amount_raised_date_itc",
    "gst_amount",
    "payment_received_date_itc",
    "total_amount_received_itc",
    "margin_pnl",
]

DATE_COLUMNS = {
    "advance_payment_date",
    "dispatch_date",
    "reached_on",
    "bill_amount_raised_date_itc",
    "payment_received_date_itc",
}

TEXT_COLUMNS = {
    "material",
    "truck_number",
    "delivery_chalan",
    "driver_mobile",
    "transporter_name",
    "lorry_receipt",
    "transporter_mobile",
    "advance_paid_to",
    "loading_location",
    "tax_invoice_number",
    "eway_bill_no",
    "wc_number",
    "bill_amount_raised_date_itc" # overridden below, kept for clarity
}
TEXT_COLUMNS.discard("bill_amount_raised_date_itc")  # this one is a date

ASSESSMENT_MAP = [
    "sr_no",
    "truck_number",
    "material_loaded",
    "loading_location",
    "dispatch_date",
    "reached_on",
    "weight_pi_yard_mt",
    "weight_itc_yard",
    "weight_loss_mt",
    "eway_bill_amt_with_gst",
    "payment_received_itc",
    "gst_amount",
    "total_amount_received",
    "difference_in_credit",
]
ASSESSMENT_DATE_COLUMNS = {"dispatch_date", "reached_on"}
ASSESSMENT_TEXT_COLUMNS = {"truck_number", "material_loaded", "loading_location"}


def sql_escape(s):
    return s.replace("'", "''")


def to_sql_value(col, value, date_cols, text_cols):
    if value is None:
        return "NULL"
    if isinstance(value, str) and value.strip() == "":
        return "NULL"
    if col in date_cols:
        if isinstance(value, (datetime.datetime, datetime.date)):
            return f"'{value.isoformat()[:10]}'"
        # value is a string like '26/13' -> not a real date, skip as NULL
        # (kept in a text sibling column would need schema change; we drop
        # unparsable dates here rather than guess).
        return "NULL"
    if col in text_cols:
        if isinstance(value, (datetime.datetime, datetime.date)):
            return f"'{sql_escape(value.isoformat()[:10])}'"
        return f"'{sql_escape(str(value).strip())}'"
    # numeric
    if isinstance(value, (datetime.datetime, datetime.date)):
        return "NULL"
    try:
        return repr(float(value))
    except (TypeError, ValueError):
        return "NULL"


def build_inserts(ws, log_type, column_map, date_cols, text_cols, header_row=2, table="log_entries", extra_cols=None):
    statements = []
    for row in ws.iter_rows(min_row=header_row + 1, max_row=ws.max_row, values_only=True):
        values = row[: len(column_map)]
        if all(v is None for v in values):
            continue
        cols = list(column_map)
        vals = [to_sql_value(c, v, date_cols, text_cols) for c, v in zip(column_map, values)]
        if extra_cols:
            for k, v in extra_cols.items():
                cols.append(k)
                vals.append(f"'{sql_escape(v)}'")
        statements.append(
            f"INSERT INTO {table} ({', '.join(cols)}) VALUES ({', '.join(vals)});"
        )
    return statements


def main():
    if len(sys.argv) < 2:
        print("Usage: python3 import_data.py /path/to/WoodHub.xlsx")
        sys.exit(1)

    src = sys.argv[1]
    wb = openpyxl.load_workbook(src, data_only=True)

    out_lines = ["-- Auto-generated by import_data.py — review before running.", "begin;"]

    if "Euca Chips Log Book" in wb.sheetnames:
        out_lines += build_inserts(
            wb["Euca Chips Log Book"], "euca_chips", COLUMN_MAP, DATE_COLUMNS, TEXT_COLUMNS,
            extra_cols={"log_type": "euca_chips"},
        )
    if "Euco Wood Log Book" in wb.sheetnames:
        out_lines += build_inserts(
            wb["Euco Wood Log Book"], "euco_wood", COLUMN_MAP, DATE_COLUMNS, TEXT_COLUMNS,
            extra_cols={"log_type": "euco_wood"},
        )
    if "Assisment Log Book" in wb.sheetnames:
        out_lines += build_inserts(
            wb["Assisment Log Book"], None, ASSESSMENT_MAP, ASSESSMENT_DATE_COLUMNS,
            ASSESSMENT_TEXT_COLUMNS, table="assessment_log",
        )

    out_lines.append("commit;")

    with open("import.sql", "w") as f:
        f.write("\n".join(out_lines))

    n = len([l for l in out_lines if l.startswith("INSERT")])
    print(f"Wrote import.sql with {n} INSERT statements.")


if __name__ == "__main__":
    main()
